name: Daily Web Scraping

on: push
#   schedule:
#     - cron: '0 13 * * *'  # Run daily at 13:00 UTC

jobs:
  web_scraping_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install bs4
        pip install selenium
        pip install gspread

    - name: Run Web Scraping Script
      run: |
        pip install get-chrome-driver --upgrade
        python ./main.py tokyo cafe
